### ISSUE TITLE
Updated PypadPlusPlus bundle with latest notepad++ and Python version every 6 months?

### ISSUE THREAD

**Issue by rakshasha-medhi** [bitagoras/PyPadPlusPlus#10]
Last evening was my third attempt to do manual installation of of PypadPlusPlus in order to have the updated on notepad++ and it was my third time failing to do so.

Is it possible to have an updated bundle every, let's say, 6 months? Last release was on May 2021, so maybe it's a great time for an update?
I love using PypadPlusPlus as my main python editor and it would be great if periodically there's an updated bundle.

Thank you for your hard work making it possible to work with python using notepad++

Cheers!

**Comment by bitagoras** [comment]
I try to update more often in future. I was actually thinking that no one is actively using this tool except me, so I did also not check the gihub notifications for a while, sorry for that.

I just did an update on newest Notepad++ and PythonScript version including Python 3.10.

**Comment by rakshasha-medhi** [comment]
thank you very much kind Sir!
I have a small Python classroom which consists of non-programming backgrounds with 20-30 students.
The 2nd class will start in the new year and I will be teaching them while using your awesome tool.

I live in a 3rd world country which means we don't have access to powerful hardware. Using Pycharm is too heavy, using your tool here is the best for my use case and most lightweight I've ever found in terms of resource requirement (I have tried most code editors and IDEs). 

So again, thanks for this update. Appreciate it!

**Comment by bitagoras** [comment]
You are very welcome and thank you for the feedback!
