### ISSUE TITLE
Keep initialization message

### ISSUE THREAD

**Issue by matthewacarson** [bitagoras/PyPadPlusPlus#13]
Hi. Is it possible to not remove the initialization message? I prefer to see what Python version is running when I start. Hopefully it's not too difficult and can be achieved with a change in an argument or two in the initialization script(s).

![Python version number](https://github.com/bitagoras/PyPadPlusPlus/assets/30172423/5e2e4b2c-c19c-4b0b-bce3-c845e085bce2)

**Comment by bitagoras** [comment]
It is easy to view the initialization message, since it is copied to the undo buffer before it is deleted. After startup just click inside the output frame and press the undo shortcut (ctrl + z). This will make the Python initialization text visible again.
