### ISSUE TITLE
Dark mode for interpreter/console

### ISSUE THREAD

**Issue by matthewacarson** [bitagoras/PyPadPlusPlus#14]
How can I set the interpreter window to dark mode? I had it set up that way in a previous installation, but I can't figure out how I did it now. Thanks in advance!

**Comment by bitagoras** [comment]
The console is provided by the [PythonScript](https://github.com/bruderstein/PythonScript/) plugin. I never used the dark mode and unfortunatelly don't know how to make the console appear dark in dark mode.

**Comment by matthewacarson** [comment]
Ok. I was able to figure it out. I think that all I needed to do was restart PyPad++. Thanks!
