### ISSUE TITLE
error when execute

### ISSUE THREAD

**Issue by francoataffarel** [bitagoras/PyPadPlusPlus#2]
when i try execute show me in console.

Python kernel not responding.

my python is python-3.8.3

in pypadstart 

pythonPath = "C:\Users\Frank\AppData\Local\Programs\Python\Python38-32\pythonw.exe"

so why?

**Comment by bitagoras** [comment]
Did you try it with
`pythonPath = r"C:\Users\Frank\AppData\Local\Programs\Python\Python38-32\pythonw.exe"` ?
The `r` is here required in front of the string when using backslashes.
