### ISSUE TITLE
No execution of local python with relative path

### ISSUE THREAD

**Issue by Kochise** [bitagoras/PyPadPlusPlus#4]
Hi, I use Python 3.9, but cannot set it to work with PyPadPlusPlus (it's only the bundled v3.8.5 that starts) :

`pythonPath = r"..\python\3.9\pythonw.exe"` (ie. #2)

Btw, what is the exact syntax for that line ? At what moment is `pyPadStart.py` called ?

Regards.

**Comment by bitagoras** [comment]
Sorry, I had no time yet to test it in Python 3.9. It is called in the init of the interpreter in the file pyPad/pyPadHost.py. The line and a parameter with the path to "pyPadClient.py" is called by subprocess.Popen.
