### ISSUE TITLE
PyPadPlusPlus Video Tutorial

### ISSUE THREAD

**Issue by cricrazy** [bitagoras/PyPadPlusPlus#9]
Hi Bitgoras, I recently created a detailed video tutorial on PyPadPlusPlus. I am really liking this interactive python environment. And I would like others to learn and use it. Would you please consider it putting on the main README page so that those who are more of visual types, can watch the tutorial and learn to use PyPadPlusPlus?

https://www.youtube.com/watch?v=qSwbavkYE3w

I have even included an image (if you choose to use it) that you can post as a video link? 

https://imgur.com/a/fOMrG9z

Thanks for creating a very useful plugin. 
Christian.

**Comment by bitagoras** [comment]
Hi Christian,

thank you so much for this awsome introduction video! I always wanted to do a similar introduction video but did not find any time. So, I am very glad that there is now a video availble where users can find more information. I have included the link to your video at the README page.

Best regards,
Christian

**Comment by cricrazy** [comment]
Bitagoras, thank you. I hope that more and more people find and use this plugin. It is an awesome plugin for Notepad++.  Let me know if you have some features in the future to test it out. I would be happy to do that.
